"""add wishlist

Revision ID: 45ad16686dad
Revises: 670abadb194a
Create Date: 2026-02-17 12:12:15.453239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ad16686dad'
down_revision: Union[str, Sequence[str], None] = '670abadb194a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'product_id')
    )
    op.alter_column('wishlists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'wishlists', ['user_id'])
    op.drop_constraint(op.f('wishlists_product_id_fkey'), 'wishlists', type_='foreignkey')
    op.drop_column('wishlists', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('wishlists_product_id_fkey'), 'wishlists', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'wishlists', type_='unique')
    op.alter_column('wishlists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('wishlist_items')
    # ### end Alembic commands ###
