"""reviews

Revision ID: 504166d16b90
Revises: c6d2a0c6d89b
Create Date: 2026-02-26 11:26:45.868887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '504166d16b90'
down_revision: Union[str, Sequence[str], None] = 'c6d2a0c6d89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'shipping_full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'shipping_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'shipping_line1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'shipping_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'shipping_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'shipping_country',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'India'::character varying"))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'shipping_country',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'India'::character varying"))
    op.alter_column('orders', 'shipping_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'shipping_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'shipping_line1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'shipping_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'shipping_full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
