"""fix product measurement relations

Revision ID: 85796c967393
Revises: 9f1c4d8a2b7e
Create Date: 2026-02-11 13:23:34.273202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85796c967393'
down_revision: Union[str, Sequence[str], None] = '9f1c4d8a2b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_measurements_id'), 'product_measurements', ['id'], unique=False)
    op.drop_constraint(op.f('product_measurements_measurement_id_fkey'), 'product_measurements', type_='foreignkey')
    op.drop_constraint(op.f('product_measurements_product_id_fkey'), 'product_measurements', type_='foreignkey')
    op.create_foreign_key(None, 'product_measurements', 'measurements', ['measurement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_measurements', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_measurements', type_='foreignkey')
    op.drop_constraint(None, 'product_measurements', type_='foreignkey')
    op.create_foreign_key(op.f('product_measurements_product_id_fkey'), 'product_measurements', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('product_measurements_measurement_id_fkey'), 'product_measurements', 'measurements', ['measurement_id'], ['id'])
    op.drop_index(op.f('ix_product_measurements_id'), table_name='product_measurements')
    # ### end Alembic commands ###
