"""add to cart

Revision ID: b781bc4a6b97
Revises: 85796c967393
Create Date: 2026-02-17 10:35:10.192862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b781bc4a6b97'
down_revision: Union[str, Sequence[str], None] = '85796c967393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('carts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('carts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'carts', ['user_id'])
    op.drop_constraint(op.f('carts_product_id_fkey'), 'carts', type_='foreignkey')
    op.drop_column('carts', 'product_id')
    op.drop_column('carts', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('carts_product_id_fkey'), 'carts', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'carts', type_='unique')
    op.alter_column('carts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('carts', 'updated_at')
    op.drop_column('carts', 'created_at')
    # ### end Alembic commands ###
