"""add seller and category to measurements

Revision ID: bb4b504b9008
Revises: eba45ba83bca
Create Date: 2026-02-09 11:59:14.976456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4b504b9008'
down_revision: Union[str, Sequence[str], None] = 'eba45ba83bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.execute("""
        UPDATE products
        SET category_id = 1
        WHERE category_id IS NULL
    """)
    # op.alter_column('products', 'seller_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.alter_column('products', 'category_id', nullable=False)
    op.create_foreign_key('fk_products_category', 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'products', type_='foreignkey')
#     op.alter_column('products', 'seller_id',
#                existing_type=sa.INTEGER(),
#                nullable=True)
#     op.drop_column('products', 'category_id')
#     # ### end Alembic commands ###
