"""add seller and category to measurements

Revision ID: e7d2957bf04f
Revises: fdbf1bd3fded
Create Date: 2026-02-05
"""

from alembic import op
import sqlalchemy as sa

# 👇 THESE TWO LINES ARE MANDATORY
revision = "e7d2957bf04f"
down_revision = "fdbf1bd3fded"
branch_labels = None
depends_on = None



def upgrade():
    # 1️⃣ Add columns as nullable first
    op.add_column(
        'measurements',
        sa.Column('seller_id', sa.Integer(), nullable=True)
    )

    op.add_column(
        'measurements',
        sa.Column('category_id', sa.Integer(), nullable=True)
    )

    # 2️⃣ Fill existing rows (IMPORTANT)
    op.execute("""
        UPDATE measurements
        SET seller_id = 1,
            category_id = 1
        WHERE seller_id IS NULL
    """)

    # 3️⃣ Make columns NOT NULL
    op.alter_column('measurements', 'seller_id', nullable=False)
    op.alter_column('measurements', 'category_id', nullable=False)

    # 4️⃣ Add foreign keys
    op.create_foreign_key(
        'fk_measurements_seller',
        'measurements',
        'users',
        ['seller_id'],
        ['id']
    )

    op.create_foreign_key(
        'fk_measurements_category',
        'measurements',
        'categories',
        ['category_id'],
        ['id']
    )

    # 5️⃣ Add unique constraint
    op.create_unique_constraint(
        'uq_measurements_name_seller_category',
        'measurements',
        ['name', 'seller_id', 'category_id']
    )


# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'e7d2957bf04f'
# down_revision: Union[str, Sequence[str], None] = 'fdbf1bd3fded'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('measurements', sa.Column('seller_id', sa.Integer(), nullable=False))
#     op.add_column('measurements', sa.Column('category_id', sa.Integer(), nullable=False))
#     op.drop_constraint(op.f('measurements_name_key'), 'measurements', type_='unique')
#     op.create_unique_constraint(None, 'measurements', ['name', 'seller_id', 'category_id'])
#     op.create_foreign_key(None, 'measurements', 'categories', ['category_id'], ['id'])
#     op.create_foreign_key(None, 'measurements', 'users', ['seller_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'measurements', type_='foreignkey')
#     op.drop_constraint(None, 'measurements', type_='foreignkey')
#     op.drop_constraint(None, 'measurements', type_='unique')
#     op.create_unique_constraint(op.f('measurements_name_key'), 'measurements', ['name'], postgresql_nulls_not_distinct=False)
#     op.drop_column('measurements', 'category_id')
#     op.drop_column('measurements', 'seller_id')
#     # ### end Alembic commands ###
